meta_product_name: "Breed Me"
meta_title: "Breed Me - Want some puppies Breed them."
meta_description: "BreedMe is the only pet matching app allows you to pick and match your next purebred mate—and it's free! Join now to start a new pet family!"
meta_image: "seo_image.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
